### ISSUE TITLE
ENH: For the smile I offer you...

### ISSUE THREAD

**Issue by davidjeddy** [ricardofiorani/php-legofy#4]
...a beer. Where shall I send it?

Thank you for this. Put a smile on my face after a long day in the office.

**Comment by ricardofiorani** [comment]
@davidjeddy hey sorry it took so long to reply !!
If you are in Berlin area please let me know and maybe we can have a couple of beers together !
Otherwise my paypal email is the same on my composer.json :)

Cheers 🍻 !!
